language: python
env:
  - DJANGO=1.10.2 DJANGO_SETTINGS_MODULE='lutrisweb.settings.local' SECRET_KEY="ThisIsMySecretThereAreOtherLikeThisButThisOneIsMine" USE_SQLITE=1
python:
  - 3.5
env:
  - BUILD=native
  - BUILD=docker
install:
  - ci/install.sh
before_script:
  - ci/before_script.sh
script:
  - ci/script.sh

# Build Notifications
# https://docs.travis-ci.com/user/notifications/
notifications:
  # Turn off email notifications entirely.
  email: false
