version: '3.4'

volumes:
  postgresql:
services:
  web:
    build:
      context: .
      args:
        - USE_SQLITE=${USE_SQLITE}
    volumes:
      - .:/app
      - /app/components
      - /app/lutris_client
      - /app/node_modules
      - /app/public
      - /app/src
      - /app/templates/docs
    ports:
      - 8000:8000
    stdin_open: true
    tty: true
    depends_on:
      - db
  db:
    image: postgres:11
    ports:
      - 5432:5432
    volumes:
      - postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 'lutris'
      POSTGRES_USER: 'lutris'
      POSTGRES_PASSWORD: 'admin'
