version: '3.4'

services:
  web_prod:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file: .env.prod
    volumes:
      - type: volume
        source: web-media
        target: /app/media
        volume:
          nocopy: true
      - type: volume
        source: web-static
        target: /app/static
    ports:
      - 8080:8080
    stdin_open: true
    tty: true
    depends_on:
      - db_prod
      - cache_prod
  nginx:
    restart: always
    image: nginx/latest
    ports:
      - "80:80"
    volumes:
      - web-static:/www/static
      - web-media:/www/media
    links:
      - web_prod:web_prod
  db_prod:
    restart: always
    image: postgres:11
    ports:
      - 5432:5432
    volumes:
      - postgresql:/var/lib/postgresql/data
    env_file: .env.prod
  cache_prod:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  postgresql:
  web-media:
  web-static:
  redisdata:
