version: '3.4'

volumes:
  postgresql:
  media:
services:
  web:
    build:
      context: .
    volumes:
      - type: volume
        source: media
        target: /app/media
        volume:
          nocopy: true
      - type: bind
        source: .
        target: /app
    ports:
      - 8000:8000
    stdin_open: true
    tty: true
    depends_on:
      - db
  db:
    image: postgres:11
    ports:
      - 5432:5432
    volumes:
      - postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 'lutris'
      POSTGRES_USER: 'lutris'
      POSTGRES_PASSWORD: 'admin'
