version: '3.4'

services:
  web_prod:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file: .env.prod
    volumes:
      - type: volume
        source: media
        target: /app/media
        volume:
          nocopy: true
    ports:
      - 8080:8080
    stdin_open: true
    tty: true
    depends_on:
      - db_prod
      - cache_prod
  nginx:
    restart: always
    image: nginx/latest
  db_prod:
    restart: always
    image: postgres:11
    ports:
      - 5432:5432
    volumes:
      - postgresql:/var/lib/postgresql/data
    env_file: .env.prod
  cache_prod:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  postgresql:
  media:
  redisdata:
